/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mesa3d.glb --transform 
Files: public/models/mesa3d.glb [3.85MB] > C:\Users\aaron\Desktop\ecommercedj\mesa3d-transformed.glb [629.46KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mesa3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_ff307507-13a9-47d8-a423-a7ffc9c6ed1a'].geometry} material={materials['tripo_material_ff307507-13a9-47d8-a423-a7ffc9c6ed1a']} />
    </group>
  )
}

useGLTF.preload('/mesa3d-transformed.glb')
